GET http://localhost:3000/usuario/perfil?t=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWI1NjVhMTZmNDRjNDVhMjM1NTRkZTMiLCJub21icmUiOiJkYXZpbCIsImFwZWxsaWRvIjoidGlxdWluIiwiZm90b0RlVXN1YXJpbyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMC9pbWcvYXZhdGFyLmpwZyIsIm5vbWJyZURlVXN1YXJpbyI6ImRhdmlsVCIsImNvcnJlb0VsZWN0cm9uaWNvIjoiZWxuaW5pMTIwQGdtYWlsLmNvbSIsImlhdCI6MTYzOTI3OTEwMX0.U48cXTqwAGUQavNTqeDgBn4WedTLhInfTdIyEKgh9Ow HTTP/1.1
Content-Type:application/json

{
    "titulo":"I have a problem",
    "contenido":"JAJAJAJAJ estupida",
    "nombre":"davil",
    "apellido":"tiquin",
    "nombreDeUsuario":"davilT",
    "correoElectronico":"elnini120@gmail.com",
    "contraseña":"123456787",
    "discapacidadVisual":true,
    "temaDeLaApp":"dark"
}